#if !canImport(ObjectiveC)
import XCTest

extension VoteKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VoteKitTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(VoteKitTests.__allTests__VoteKitTests),
    ]
}
#endif
